/**
 * Handles toggling the navigation menu for small screens.
 */
(function () {
  var button = document.getElementById("topnav").getElementsByTagName("div")[0],
    menu = document.getElementById("topnav").getElementsByTagName("ul")[0];

  if (undefined === button) return false;

  // Hide button if menu is missing or empty.
  if (undefined === menu || !menu.childNodes.length) {
    button.style.display = "none";
    return false;
  }

  button.onclick = function () {
    if (-1 == menu.className.indexOf("clg-menu")) menu.className = "clg-menu";

    if (-1 != button.className.indexOf("toggled-on")) {
      button.className = button.className.replace(" toggled-on", "");
      menu.className = menu.className.replace(" toggled-on", "");
    } else {
      button.className += " toggled-on";
      menu.className += " toggled-on";
    }
  };
})();

// Get random hero image on page load
function getHeroImage() {
  //declare an array
  var randomImage = new Array();

  //insert the URL of images in array
  randomImage[0] = "./assets/img/seamstress.jpg";
  randomImage[1] = "./assets/img/asian-mom-baby-business.jpg";
  randomImage[2] = "./assets/img/black-men-workshop.jpg";
  randomImage[3] = "./assets/img/couple-coffeeshop.jpg ";
  randomImage[4] = "./assets/img/man-carpentry-business.jpg";
  randomImage[5] = "./assets/img/hispanic-mom-baby-business.jpg";

  //generate a number
  var number = Math.floor(Math.random() * randomImage.length);

  //return the images generated by number
  document.querySelector(
    ".hero"
  ).style.backgroundImage = `url('${randomImage[number]}')`;
}
getHeroImage();
